-- MySQL Script generated by MySQL Workbench
-- Mon 12 Oct 2015 23:18:52 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fastpress_app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fastpress_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fastpress_app` DEFAULT CHARACTER SET latin1 ;
USE `fastpress_app` ;

-- -----------------------------------------------------
-- Table `fastpress_app`.`blogs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fastpress_app`.`blogs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `slug` VARCHAR(255) NOT NULL COMMENT '',
  `title` VARCHAR(255) NOT NULL COMMENT '',
  `tags` VARCHAR(255) NOT NULL COMMENT '',
  `content` TEXT NOT NULL COMMENT '',
  `date_added` DATETIME NOT NULL COMMENT '',
  `is_active` BIT(1) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = latin1
COMMENT = '	';


-- -----------------------------------------------------
-- Table `fastpress_app`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fastpress_app`.`tags` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `tag` VARCHAR(80) NOT NULL COMMENT '',
  `blog_id` INT(11) NOT NULL COMMENT '',
  `date_added` DATE NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 59
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fastpress_app`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fastpress_app`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(100) NOT NULL COMMENT '',
  `email` VARCHAR(255) NOT NULL COMMENT '',
  `password` VARCHAR(255) NOT NULL COMMENT '',
  `is_admin` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
