-- MySQL Script generated by MySQL Workbench
-- Sun 11 Oct 2015 12:44:55 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fastpress
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fastpress
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fastpress` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `fastpress` ;

-- -----------------------------------------------------
-- Table `fastpress`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fastpress`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(100) NOT NULL COMMENT '',
  `email` VARCHAR(255) NOT NULL COMMENT '',
  `password` VARCHAR(255) NOT NULL COMMENT '',
  `is_admin` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fastpress`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fastpress`.`tags` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `tag` VARCHAR(80) NOT NULL COMMENT '',
  `blog_id` INT(11) NOT NULL COMMENT '',
  `date_added` DATE NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 59
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fastpress`.`blogs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fastpress`.`blogs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `slug` VARCHAR(255) NOT NULL COMMENT '',
  `title` VARCHAR(255) NOT NULL COMMENT '',
  `tags` VARCHAR(255) NOT NULL COMMENT '',
  `content` TEXT NOT NULL COMMENT '',
  `date_added` DATETIME NOT NULL COMMENT '',
  `is_active` BIT(1) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = latin1
COMMENT = '	';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
