-- MySQL Script generated by MySQL Workbench
-- Sun 11 Oct 2015 12:59:14 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fastpress
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fastpress
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fastpress` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `fastpress` ;

-- -----------------------------------------------------
-- Table `fastpress`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fastpress`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(100) NOT NULL COMMENT '',
  `email` VARCHAR(255) NOT NULL COMMENT '',
  `password` VARCHAR(255) NOT NULL COMMENT '',
  `is_admin` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fastpress`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fastpress`.`tags` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `tag` VARCHAR(80) NOT NULL COMMENT '',
  `date_added` DATE NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 59
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fastpress`.`pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fastpress`.`pages` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `slug` VARCHAR(255) NOT NULL COMMENT '',
  `title` VARCHAR(255) NOT NULL COMMENT '',
  `content` TEXT NOT NULL COMMENT '',
  `date_added` DATETIME NOT NULL COMMENT '',
  `is_active` BIT(1) NOT NULL COMMENT '',
  `user_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_page_users_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_page_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `fastpress`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = latin1
COMMENT = '	';


-- -----------------------------------------------------
-- Table `fastpress`.`pages_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fastpress`.`pages_tags` (
  `pages_id` INT(11) NOT NULL COMMENT '',
  `tags_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`pages_id`, `tags_id`)  COMMENT '',
  INDEX `fk_pages_has_tags_tags1_idx` (`tags_id` ASC)  COMMENT '',
  INDEX `fk_pages_has_tags_pages1_idx` (`pages_id` ASC)  COMMENT '',
  CONSTRAINT `fk_pages_has_tags_pages1`
    FOREIGN KEY (`pages_id`)
    REFERENCES `fastpress`.`pages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pages_has_tags_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `fastpress`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
